server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3311/security?serverTimezone=Asia/Seoul
    username: cos1234
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate  #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true